// Art styles configuration for image generation

export const artStyles = {
  "Ukiyo-e": "Ukiyo-e style, Japanese woodblock print medium, flat layered colors, bold black outlines with intricate patterns, floating world themes of nature, kabuki actors, Mount Fuji, great wave, cherry blossoms, Edo period serenity, in the style of Hokusai, in the style of Hiroshige",
  "Photorealism": "photorealistic rendering, hyper-detailed high-resolution 8K or 16K photography medium, sharp focus on lifelike textures and reflections, natural diffused or studio lighting, meticulous skin pores and fabric weaves, shot on Hasselblad H6D-400c, Phase One XF, or large format camera",
  "Hyperrealism": "hyperrealistic attention to surface and light, detailed textures, cinematic lighting, objects and environments, full-body or scene, product or still-life realism, sculptural accuracy, in the style of Ron Mueck (sculpture), Chuck Close (pattern), and contemporary hyperrealists",
  "Digital Art": "digital painting medium, concept art with ArtStation trends, CGI and 3D rendering in Unreal Engine 5, Octane render glows and VFX effects, high-fantasy dynamic lighting, sculpted in ZBrush",
  "Abstract Expressionism": "abstract expressionist oil or acrylic medium, bold gestural brushstrokes and drip splatters, non-representational chaotic energy on large canvas, vibrant emotional palettes, in the style of Jackson Pollock, in the style of Willem de Kooning",
  "Art Deco": "Art Deco graphic design medium, geometric symmetrical patterns with streamlined motifs, gold-black metallic tones and zigzags, 1920s luxurious glamour, stylized figures and elegant sans-serif typography",
  "Art Nouveau": "Art Nouveau illustration medium, organic flowing whiplash lines and curves, stylized floral vines in pastel jewel tones, elegant sinuous forms with natural inspiration, in the style of Alphonse Mucha, in the style of Gustav Klimt",
  "Baroque": "Baroque oil painting medium, dramatic chiaroscuro and tenebrism shadows, intense emotional opulence in rich deep colors, dynamic swirling compositions, in the style of Caravaggio, in the style of Rembrandt",
  "Bauhaus": "Bauhaus design medium, minimalist geometric abstraction in primary colors (red, yellow, blue), clean functional lines with industrial modernism, asymmetrical balance and sans-serif type",
  "Cubism": "Cubist mixed media, fragmented geometric facets from multiple perspectives, abstracted forms in monochromatic earthy tones, analytical deconstruction of reality, in the style of Pablo Picasso, in the style of Georges Braque",
  "Expressionism": "Expressionist canvas medium, distorted emotional forms with swirling bold strokes, vivid non-naturalistic colors evoking angst, raw psychological depth, in the style of Edvard Munch, in the style of Ernst Ludwig Kirchner",
  "Fauvism": "Fauvist oil medium, wild expressive brushwork in intense vibrant colors, bold non-naturalistic contrasts, painterly joyful freedom, in the style of Henri Matisse, in the style of André Derain",
  "Impressionism": "Impressionist plein air medium, loose visible brushstrokes capturing dappled light, soft atmospheric focus on fleeting moments, pastel outdoor palettes, in the style of Claude Monet, in the style of Pierre-Auguste Renoir",
  "Minimalism": "minimalist sculpture or canvas medium, extreme reduction to monochromatic forms, clean geometric lines with vast negative space, uncluttered meditative simplicity, in the style of Donald Judd, in the style of Agnes Martin",
  "Pop Art": "Pop Art silkscreen medium, bold bright colors with Ben-Day dots and halftones, comic-inspired mass culture irony, vibrant consumer icons, in the style of Andy Warhol, in the style of Roy Lichtenstein",
  "Renaissance": "Renaissance fresco or oil medium, classical realism with sfumato blending and linear perspective, harmonious mythological scenes, balanced golden ratio compositions, in the style of Leonardo da Vinci, in the style of Raphael",
  "Romanticism": "Romanticist landscape medium, dramatic sublime nature with emotional turmoil, stormy atmospheric depths and ancient ruins, awe-inspiring light effects, in the style of J.M.W. Turner, in the style of Caspar David Friedrich",
  "Surrealism": "Surrealist dream canvas medium, bizarre uncanny juxtapositions with melting forms, precise subconscious symbols in illogical scenes, in the style of Salvador Dalí, in the style of René Magritte",
  "Street Art": "street art spray paint medium, large mural stencils on urban walls, bold vibrant political commentary, layered graffiti textures, in the style of Banksy, in the style of Shepard Fairey",
  "Graffiti": "graffiti aerosol medium, explosive bold colors with drips and wildstyle tags, street culture energy on concrete, high-contrast rebellious outlines",
  "Dadaism": "Dadaist collage medium, absurd anti-art assemblages and readymades, nonsensical avant-garde satire, chaotic experimental juxtapositions, in the style of Marcel Duchamp, in the style of Hannah Höch",
  "Constructivism": "Constructivist poster medium, geometric industrial shapes in red-black-white, abstract propaganda motifs with dynamic asymmetry, in the style of El Lissitzky, in the style of Aleksandr Rodchenko",
  "Futurism": "Futurist dynamic medium, speed and mechanization with multiple exposures, diagonal thrusting lines in vibrant fragmented energy, machine-age futurism, in the style of Umberto Boccioni, in the style of Giacomo Balla",
  "Synthwave": "Synthwave digital medium, 1980s retro-futuristic neon gradients, gridlines with outrun palm vibes, cyberpunk nostalgia and synth glows",
  "Vaporwave": "Vaporwave glitch medium, pastel 80s/90s gradients with Greek statues, lo-fi surreal nostalgia, ironic consumer glitches and palm malls",
  "Cyberpunk": "Cyberpunk neon digital medium, dystopian megacity with rainy reflections, high-tech holograms and low-life grit, in the style of Blade Runner, in the style of Ghost in the Shell",
  "Pixel Art": "pixel art digital medium, 8-bit blocky low-res sprites, limited retro palette, nostalgic arcade stylization and chiptune vibes",
  "Low Poly": "low poly 3D modeling medium, faceted geometric polygons with minimal edges, stylized vibrant renders, Unity or Blender abstract simplicity",
  "Watercolor": "watercolor paper medium, soft bleeding edges with transparent wet-on-wet layers, diffused ethereal delicacy, light airy hand-painted washes",
  "Oil Painting": "oil on canvas medium, thick impasto textures with layered vibrant colors, expressive dramatic lighting and depth, in the style of Vincent van Gogh",
  "Ink Drawing": "ink on paper medium, precise fine lines with crosshatching shading, monochrome intricate details, illustrative black-and-white precision",
  "Charcoal Sketch": "charcoal on paper medium, grayscale rough expressive marks, heavy smudged tonal variations, raw emotional gestural intensity",
  "Comic Book": "comic book inked medium, bold outlined panels with flat vibrant colors, speech bubbles and halftone action, dynamic superhero poses",
  "Anime": "anime cel animation medium, large expressive eyes with clean fluid lines, vibrant emotional close-ups, in the style of Studio Ghibli",
  "Manga": "manga ink medium, black-and-white high-contrast panels, screentone shading with action speed lines, dramatic sequential poses",
  "Concept Art": "concept art digital medium, detailed imaginative fantasy designs, cinematic layered compositions, game or film pre-vis painting",
  "Steampunk": "steampunk mixed media, Victorian gears and brass tech, brown-copper alternate history palette, adventurous mechanical details",
  "Gothic": "Gothic architectural medium, dark moody pointed arches, medieval stained glass shadows, eerie mystical dramatic lighting",
  "Art Brut": "art brut raw medium, outsider unrefined expressive forms, intense personal symbolism in naive visceral energy, in the style of Jean Dubuffet",
  "Dreamlike": "dreamlike ethereal medium, soft-focus haze with floating surreal elements, atmospheric mysterious pastels, subconscious narratives",
  "Pop Surrealism": "pop surrealism lowbrow medium, playful bizarre candy colors, whimsical dark miniatures, in the style of Mark Ryden, in the style of Audrey Kawasaki",
  "Children's Book": "children's book illustration medium, whimsical hand-drawn bright colors, friendly rounded playful scenes, storybook magic",
  "Photobash": "photobash digital collage medium, manipulated surreal photo layers, high-detail concept fusion of real and imagined elements",
  "Disney": "Disney animation medium, classic cartoon friendly exaggerations, vibrant family magical worlds, iconic whimsical designs",
  "Studio Ghibli": "Studio Ghibli hand-drawn medium, soft warm lush backgrounds, whimsical magical realism harmony, in the style of Hayao Miyazaki",
  "Colouring Book Page": "colouring book line art medium, bold black vector outlines with intricate fillable patterns, no shading on white background, simple stylized shapes, printable therapeutic designs, adult mandala or zentangle motifs, in the style of Dover publications",
  "Movie Poster": "movie poster graphic medium, dramatic cinematic composition with bold typography and billing block, high-contrast promotional lighting and title treatment, theatrical release flair, in the style of Drew Struzan, Saul Bass minimalist, or Polish film posters, IMAX format",
  "Blueprint": "blueprint technical medium, cyanotype white lines on Prussian blue background, precise architectural schematics with labels and dimensions, engineering diagram precision, isometric views, CAD wireframe, construction documents",
  "Technical Drawing": "technical drawing ink medium, isometric or orthographic views with ruled lines and annotations, exploded cross-sections, mechanical patent-style accuracy, black ink on vellum, precise linework, ISO standards, assembly instructions",
  "Stained Glass Window": "stained glass mosaic medium, vibrant lead came lines and translucent color panels, glowing backlit fragmentation, medieval religious iconography or Gothic cathedral motifs, light streaming effects, in the style of Tiffany or Art Nouveau glass, rose window designs",
  "Soviet Propaganda Poster": "Soviet propaganda lithograph medium, bold heroic red-yellow figures with Cyrillic text, socialist realism and constructivist elements, 1920s-1980s USSR aesthetics, hammer and sickle, Lenin portraits, revolutionary worker glorification",
  "Forensic Sketch": "forensic sketch pencil medium, monochromatic facial composites, subtle shading for witness accuracy, investigative realistic features",
  "Patent Illustration": "patent illustration line medium, clean exploded invention views, numbered arrows and labels, black-and-white archival precision",
  "Cave Painting": "cave painting pigment medium, prehistoric earthy ochre silhouettes, simple ritualistic animals and hand stencils on rock surfaces",
  "Tarot Card": "tarot card illustrative medium, symbolic ornate borders with esoteric archetypes, gold mystical symbols, Rider-Waite Renaissance vibe",
  "Victorian Illustration": "Victorian engraving medium, intricate romanticized lines with floral vignettes, sepia muted tones, in the style of Arthur Rackham",
  "Psychedelic": "psychedelic poster medium, swirling acid color fractals, optical hallucinogenic illusions, 1960s counterculture energy, in the style of Peter Max",
  "Rococo": "Rococo decorative medium, ornate playful pastel curves, frivolous rocaille shells and aristocratic scenes, light airy elegance, in the style of François Boucher",
  "Pointillism": "pointillism dotted medium, optical mixing of pure hue dots, scientific vibrant precision, seascape or portrait optics, in the style of Georges Seurat",
  "Byzantine": "Byzantine icon medium, gold-leaf flat stylized figures, religious halo mosaics, hierarchical tesserae compositions",
  "Folk Art": "folk art handcrafted medium, naive bright primary motifs, cultural rustic symbols, regional simplicity like Mexican tin or Scandinavian wood",
  "Op Art": "Op Art geometric medium, black-and-white vibrating patterns, moiré optical illusions, perceptual abstract trickery, in the style of Bridget Riley",
  "Kinetic Art": "kinetic sculpture medium, movable modular elements implying motion, metallic abstract dynamism, interactive wind or motor effects, in the style of Alexander Calder, Theo Jansen mobiles",
  "Land Art": "land art environmental medium, site-specific earthworks like spirals, aerial natural scale installations, ephemeral landscape interventions with natural materials, in the style of Robert Smithson, Andy Goldsworthy, Spiral Jetty aesthetics",
  "Naive Art": "naive art self-taught medium, childlike flat bright distortions, whimsical everyday scenes, primitive joyful perspective, in the style of Henri Rousseau",
  "Trompe-l'œil": "trompe-l'œil illusion medium, hyper-detailed fool-the-eye realism, painted deceptions on walls, classical surface mimicry",
  "Woodcut": "woodcut print medium, bold carved high-contrast lines, textured grain folk illustrations, antique ink relief, in the style of Albrecht Dürer",
  "Linocut": "linocut relief medium, bold graphic carved linoleum with high contrast, visible tool marks and reduction prints, German Expressionist energy, in the style of Pablo Picasso, block printing textures",
  "Neon": "neon light medium, glowing electric tubes in vibrant colors, dark background with bright illumination, retro signage aesthetic, cyberpunk atmosphere",
  "Holographic": "holographic medium, iridescent rainbow reflections, prismatic light effects, futuristic metallic surfaces, shifting color spectrum",
  "Glitch Art": "glitch art digital medium, corrupted data aesthetics, pixelated distortions, RGB channel separation, digital noise and artifacts",
  "Voxel Art": "voxel art 3D medium, cubic pixel blocks in isometric view, Minecraft-style construction, retro gaming aesthetic",
  "Paper Cut": "paper cut craft medium, layered paper silhouettes, shadow box depth, delicate cutout patterns, handmade texture",
  "Origami": "origami paper folding medium, geometric paper sculptures, clean angular folds, minimalist Japanese aesthetic",
  "Mosaic": "mosaic tile medium, small colored pieces forming larger image, ancient Roman or Byzantine style, tessellated patterns",
  "Stencil": "stencil spray paint medium, bold graphic shapes with clean edges, street art aesthetic, high contrast silhouettes",
  "Embroidery": "embroidery textile medium, colorful thread stitching on fabric, folk art patterns, handcrafted texture",
  "Batik": "batik wax-resist medium, Indonesian textile art, flowing organic patterns, earthy dye colors",
  "Tie-Dye": "tie-dye fabric medium, psychedelic swirling colors, 1960s hippie aesthetic, organic flowing patterns",
  "Grunge": "grunge texture medium, distressed and weathered surfaces, rough edges, alternative rock aesthetic",
  "Vintage": "vintage photography medium, aged sepia tones, film grain texture, nostalgic retro styling",
  "Polaroid": "Polaroid instant photo medium, square format with white border, faded colors, authentic film aesthetic",
  "Film Noir": "film noir cinematic medium, high contrast black and white, dramatic shadows, 1940s detective aesthetic",
  "Sepia": "sepia tone photography medium, warm brown monochrome, vintage aged appearance, historical documentation style",
  "Cross-Hatch": "cross-hatch ink medium, overlapping line patterns for shading, traditional illustration technique, detailed linework",
  "Stippling": "stippling dot technique medium, pointillistic shading with small dots, detailed pen and ink illustration",
  "Scratchboard": "scratchboard engraving medium, white lines scratched into black surface, high contrast detailed illustration",
  "Lithograph": "lithograph printing medium, smooth tonal gradations, fine art reproduction quality, stone printing technique",
  "Etching": "etching intaglio medium, fine line engraving on metal plate, classical printmaking technique, detailed crosshatching",
  "Aquatint": "aquatint etching medium, tonal areas with granular texture, atmospheric effects, fine art printmaking",
  "Mezzotint": "mezzotint engraving medium, rich velvety blacks with smooth tonal transitions, portrait printmaking technique",
  "Screen Print": "screen print medium, bold flat colors with slight texture, pop art aesthetic, commercial printing style",
  "Risograph": "risograph printing medium, vibrant flat colors with slight registration errors, zine aesthetic, DIY printing",
  "Cyanotype": "cyanotype photographic medium, Prussian blue monochrome, sun printing technique, botanical specimens",
  "Daguerreotype": "daguerreotype photography medium, mirror-like silver surface, 19th century portrait style, historical process",
  "Tintype": "tintype photography medium, metal plate with dark background, Civil War era portraits, antique process",
  "Double Exposure": "double exposure photography medium, overlapping transparent images, dreamy surreal effects, film technique",
  "Long Exposure": "long exposure photography medium, motion blur and light trails, smooth water and clouds, time-based effects",
  "Macro": "macro photography medium, extreme close-up detail, shallow depth of field, magnified textures and patterns",
  "Tilt-Shift": "tilt-shift photography medium, selective focus creating miniature effect, shallow depth of field, toy-like appearance",
  "HDR": "HDR photography medium, high dynamic range with enhanced contrast, surreal color saturation, detailed shadows and highlights",
  "Infrared": "infrared photography medium, false color spectrum, white foliage and dark skies, otherworldly appearance"
};
